baseurl = "https://qiqi789.netlify.app"
languageCode = "en-us"
title = "齐琦 Qi QI's Website"
author = "Qi Qi"


theme = "hugo-theme-tokiwa"
googleAnalytics = "G-CQ1LVQ4JCK"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

copyright = "Copyright © 2026"
#disqusShortname = "YOURSHORTNAME"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
hasCJKLanguage = true
#languageCode = "cn"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true  # for raw html codes can be included.


[permalinks]
    post = "/:year/:month/:day/:slug/"

[menu]
# Shown in the side menu.
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Research and Publication"
    url = "/research/"
    weight = 1
[[menu.main]]
    name = "Courses Taught"
    url = "/courses/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Advisees"
    url = "/advisees/"
    weight = 4
[[menu.main]]
    name = "Links"
    url = "/venues/"
    weight = 5
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[params]
    description = "![](images/photo_mit_3.png) <br>  你好！我在海南大学计算机科学与技术学院教授算法与博弈问题、人工智能、网络安全技术等课程。我的研究兴趣主要在组合优化问题与博弈问题，相关应用在计算机科学、经济、社会、心理学、工业，和网络空间安全等领域。专业领域包括算法博弈、机器学习和数据科学。我在美国密苏里哥伦比亚大学获得计算机科学哲学博士学位，我的导师是[Yi Shang](https://engineering.missouri.edu/faculty/yi-shang/)。我的电子邮件地址Email： qqi@hainanu.edu.cn"
    
    #description = "![](images/photo_mit_3.png) <br>  我的研究兴趣主要集中在近似算法，组合优化决策，鲁棒优化，随机规划，和机器学习算法。我在海南大学计算机科学与技术学院教授人工智能，从事相关领域科学研究工作。我之前在美国密苏里大学哥伦比亚校区获得计算机科学哲学博士学位。如果对算法与博弈，数据建模预测，运筹优化等领域感兴趣，欢迎联系 Email： qqi@hainanu.edu.cn"
    
    math = true # for introducing $KaTEX$
    env = "production" # for Google Analytics and DISQUS.
    useChineseFonts = true # for font Noto Serif etc.
    postDateFormat = "2006-1-2" # override custom date format posts.
    
    images = ['photo_mit_3.png']
    
    mainSectionTitle = "Research page"
    mainSection = "research"
    
    showAllPostsOnHomePage = false
    #postsOnHomePage = 21
    mainSections = ['post', 'courses', 'research']
    tagsOverview = true
    showAllPostsArchive = true # or false (default)
    
    
    # Post page settings
    show_updated = true # default
    showReadTime = true # default
  

    # options for highlight.js (version, additional languages, and theme)
    #highlightjsVersion = "9.12.0"
    #highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #highlightjsLang = ["r", "yaml"]
    #highlightjsTheme = "github"

    #MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.png" # "favicon.ico"
    
    
    colortheme = "white" # "white" # dark, light, white, or classic
    
    iconFont = "mono-social"
    socialIconStyle = "circle"
    
    [params.logo]
    url = "myweb.png"
    width = 50
    height = 50
    alt = "Logo"
    

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[social]
mail = "mailto:qqi@hainanu.edu.cn"
#zhihu = "http://example.com/"

  
## my edit
enableEmoji= true
hasCJKLanguage = true



    
[frontmatter]
  images = ['static/images']
  
    
    
