[context.production.environment]
  #HUGO_VERSION = "0.83.1"
  #HUGO_VERSION = "0.96.0"
  #HUGO_VERSION = "0.105.0"
  HUGO_VERSION = "0.154.5"
  
[context.deploy-preview.environment]
  HUGO_VERSION = "0.154.5"